import { BrainCircuit, Cpu, Zap, ListChecks, History } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import useCrmStore from '@/stores/useCrmStore'

export default function IA() {
  const { state } = useCrmStore()

  // Filter interactions automatically generated by the IA specifically related to objections
  const iaLogs = state.interactions.filter((i) => i.author === 'The Brain (IA)')

  return (
    <div className="space-y-6 bg-fuchsia-50/20 min-h-[calc(100vh-6rem)] p-2 md:p-6 rounded-xl border border-fuchsia-100/50">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-white/80 backdrop-blur-md p-6 rounded-xl border border-fuchsia-100 shadow-sm">
        <div className="flex items-center gap-4">
          <div className="bg-fuchsia-100/60 p-3 rounded-xl border border-fuchsia-200/50 text-fuchsia-600 shadow-sm">
            <BrainCircuit className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-3xl font-bold tracking-tight text-fuchsia-950">
              The Brain (IA Central)
            </h1>
            <p className="text-fuchsia-700/80 font-medium mt-1">
              Visão global e Auditoria de Inteligência Artificial do CRM.
            </p>
          </div>
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <Card className="bg-white/80 shadow-sm border-fuchsia-100 backdrop-blur-sm">
          <CardHeader className="pb-2">
            <CardTitle className="text-lg flex items-center gap-2 text-fuchsia-900">
              <Cpu className="w-5 h-5 text-fuchsia-500" /> Modelos Ativos
            </CardTitle>
            <CardDescription>Resumo de processamento diário</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 pt-4">
            <div className="flex justify-between items-center border-b border-fuchsia-50 pb-2">
              <span className="text-sm font-medium text-slate-600">Leads Analisados (Hoje)</span>
              <span className="font-bold text-fuchsia-700">142</span>
            </div>
            <div className="flex justify-between items-center border-b border-fuchsia-50 pb-2">
              <span className="text-sm font-medium text-slate-600">Objeções Interceptadas</span>
              <span className="font-bold text-fuchsia-700">{iaLogs.length + 314}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-sm font-medium text-slate-600">Precisão Média de FIT</span>
              <span className="font-bold text-emerald-600">94.2%</span>
            </div>
          </CardContent>
        </Card>

        <Card className="md:col-span-2 bg-gradient-to-br from-fuchsia-500 to-indigo-600 text-white shadow-md border-none overflow-hidden relative">
          <div className="absolute -right-10 -bottom-10 opacity-10">
            <Zap className="w-48 h-48" />
          </div>
          <CardHeader>
            <CardTitle className="text-white/90">Eficácia das Copys Sugeridas</CardTitle>
            <CardDescription className="text-fuchsia-100">
              Taxa de resposta de leads utilizando mensagens geradas pela IA.
            </CardDescription>
          </CardHeader>
          <CardContent className="relative z-10 pt-4 flex flex-col sm:flex-row items-end gap-6">
            <div className="bg-white/20 p-6 rounded-xl backdrop-blur-md border border-white/10 flex-1 w-full">
              <p className="text-sm uppercase tracking-wider font-semibold text-fuchsia-100 mb-1">
                Taxa de Abertura
              </p>
              <p className="text-4xl font-black">68%</p>
            </div>
            <div className="bg-white/20 p-6 rounded-xl backdrop-blur-md border border-white/10 flex-1 w-full">
              <p className="text-sm uppercase tracking-wider font-semibold text-fuchsia-100 mb-1">
                Conversão para Call
              </p>
              <p className="text-4xl font-black">24%</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card className="bg-white/80 shadow-sm border-fuchsia-100 backdrop-blur-sm">
        <CardHeader className="border-b border-fuchsia-50 bg-fuchsia-50/30">
          <CardTitle className="text-lg flex items-center gap-2 text-fuchsia-900">
            <History className="w-5 h-5 text-fuchsia-600" /> Log de Auditoria e Resoluções da IA
          </CardTitle>
          <CardDescription>
            Registro centralizado de todas as interações onde The Brain interceptou objeções.
          </CardDescription>
        </CardHeader>
        <CardContent className="p-0">
          {iaLogs.length === 0 ? (
            <div className="p-8 text-center text-slate-500 font-medium flex items-center justify-center flex-col gap-2">
              <Zap className="w-8 h-8 text-slate-300" />
              Nenhuma intervenção registrada recentemente. Simule uma objeção na página 360º de uma
              Empresa para ver o The Brain em ação.
            </div>
          ) : (
            <div className="divide-y divide-fuchsia-50 max-h-[400px] overflow-y-auto">
              {iaLogs.map((log) => {
                const company = state.companies.find((c) => c.id === log.companyId)
                return (
                  <div key={log.id} className="p-5 hover:bg-fuchsia-50/20 transition-colors">
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-bold text-fuchsia-900 flex items-center gap-2">
                        {log.subject}
                      </h4>
                      <span className="text-xs font-semibold text-slate-500 bg-slate-100 px-2 py-1 rounded">
                        {log.date}
                      </span>
                    </div>
                    <div className="text-sm text-slate-600 mb-3 font-medium">
                      Empresa Alvo:{' '}
                      <span className="text-indigo-600 font-bold">
                        {company?.nomeFantasia || 'Desconhecida'}
                      </span>
                    </div>
                    <div className="bg-white p-4 rounded-lg border border-fuchsia-100 shadow-sm whitespace-pre-wrap text-sm text-slate-700 leading-relaxed">
                      {log.content}
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
